[build]
  command = "cd doc && yarn install --frozen-lockfile &&  yarn build"
  publish = "doc/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false