packages:
  - doc

allowBuilds:
  '@asyncapi/cli': set this to true or false
  '@hyperjump/json-pointer': set this to true or false
  '@hyperjump/json-schema': set this to true or false
  '@hyperjump/json-schema-core': set this to true or false
  '@hyperjump/pact': set this to true or false
  '@parcel/watcher': true
  '@scarf/scarf': set this to true or false
  core-js: true
  cypress: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  yarn: set this to true or false

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - cypress
  - esbuild
  - sharp
  - unrs-resolver
