enum AnonymousSchema_236 {
  BOARDING = 'BOARDING',
  JOURNEY_CANCELLED = 'JOURNEY_CANCELLED',
  LEAVING = 'LEAVING',
  PENDING = 'PENDING',
  STOP_CANCELLED = 'STOP_CANCELLED',
  TIME_BASED = 'TIME_BASED',
}
export default AnonymousSchema_236;
