/* eslint-disable @typescript-eslint/no-redundant-type-constituents */
export { operations as RealtimeRestOperations } from './realtimerest.d.ts';

import type { Feature, Point } from 'geojson';

import type BufferMessage from './realtime-asyncapi-types/BufferMessage';
import type DeletedVehicleMessage from './realtime-asyncapi-types/DeletedVehicleMessage';
import type FullTrajectory from './realtime-asyncapi-types/FullTrajectory';
import type FullTrajectoryCollection from './realtime-asyncapi-types/FullTrajectoryCollection';
import type FullTrajectoryCollectionProperties from './realtime-asyncapi-types/FullTrajectoryCollectionProperties';
import type FullTrajectoryProperties from './realtime-asyncapi-types/FullTrajectoryProperties';
import type Line from './realtime-asyncapi-types/Line';
import type PartialTrajectoryMessage from './realtime-asyncapi-types/PartialTrajectoryMessage';
import type StopSequence from './realtime-asyncapi-types/StopSequence';
import type StopSequenceCall from './realtime-asyncapi-types/StopSequenceCall';
import type StopSequenceMessage from './realtime-asyncapi-types/StopSequenceMessage';
import type TCallStateEnum from './realtime-asyncapi-types/TCallStateEnum';
import type TmotCode from './realtime-asyncapi-types/TmotCode';
import type TrackerTrajectory from './realtime-asyncapi-types/TrackerTrajectory';
import type TrackerTrajectoryProperties from './realtime-asyncapi-types/TrackerTrajectoryProperties.js';
import type TTrainStateEnum from './realtime-asyncapi-types/TTrainStateEnum';
import type { components } from './realtimerest.d.ts';

export declare type RealtimeChannelModeSuffix = '_schematic' | '';

export declare type RealtimeMode = 'raw' | 'schematic' | 'topographic';

export type RealtimeTrainsByRouteIdentifierResult =
  components['schemas']['TrainsByRouteIdentifierResult'];

export type RealtimeTrajectoryCollection =
  components['schemas']['TrajectoryCollection'];

export type RealtimeRouteIdentifierMatch =
  components['schemas']['RouteIdentifierMatch'];

/**
 * @type RealtimeBbox
 */
export type RealtimeBbox = (number | string)[];

export type RealtimeBuffer = [number, number];

export type RealtimeBufferResponse = BufferMessage;

export type RealtimeChannelName =
  | 'buffer'
  | 'extra_geoms'
  | 'healthcheck'
  | 'line'
  | 'websocket'
  | `deleted_vehicles${RealtimeChannelModeSuffix}`
  | `full_trajectory${RealtimeChannelModeSuffix}_${RealtimeTenant}_${RealtimeTrainId}`
  | `stopsequence_${RealtimeTenant}_${RealtimeTrainId}`
  | `timetable_${RealtimeStationId}`
  | `trajectory${RealtimeChannelModeSuffix}`;

export type RealtimeDeletedVehiclesResponse = DeletedVehicleMessage;

export interface RealtimeDeparture {
  aimedArrivalTime?: number;
  aimedDepartureTime?: number;
  arrivalDelay?: number;
  arrivalTime?: number;
  at_station_ds100?: string; // TODO Verify it still exists
  at_stoppoint: string;
  call_id: number;
  changes: unknown[];
  created_at: number;
  departureDelay?: number;
  departureTime?: number;
  formation?: unknown;
  fzo_estimated_time: number;
  has_fzo: boolean;
  has_realtime_journey: boolean;
  journey_start_time?: number;
  line: RealtimeLine;
  min_arrival_time?: number;
  new_to?: boolean; // TODO Verify it still exists
  next_stoppoints: string[];
  no_stop_between?: boolean; // TODO Verify it still exists
  no_stop_till?: unknown; // TODO Verify it still exists
  operator_provides_fzo: boolean;
  platform?: string;
  ris_aimed_time?: number;
  ris_estimated_time?: number;
  state: RealtimeStopState; /// (BOARDING|STOP_CANCELLED|JOURNEY_CANCELLED|HIDDEN)/
  tenant: RealtimeTenant;
  time?: number;
  timediff?: number; // TODO Verify it still exists
  timestamp?: number; // TODO Verify it still exists
  to: string[];
  train_id: RealtimeTrainId;
  train_number?: number;
  train_type?: number;
  updated_at: number;
  vehicle_mode?: string;
}

export interface RealtimeDepartureExtended extends RealtimeDeparture {
  cancelled?: boolean; // value generated by RealtimeAPI class
}

export type RealtimeElevatorState = 'ALL_OPERABLE' | string;

export interface RealtimeExtraGeom extends Feature {
  properties: RealtimeExtraGeomProperties;
}

export interface RealtimeExtraGeomDeleted {
  properties: RealtimeExtraGeomProperties;
  type: 'Deleted';
}

export interface RealtimeExtraGeomProperties {
  ref: number | string;
}

export type RealtimeExtraGeoms = Record<string, Feature[]>;

export interface RealtimeExtraGeomsResponse {
  client_reference: null;
  content: RealtimeExtraGeom | RealtimeExtraGeomDeleted;
  source: `extra_geoms`;
  timestamp: number;
}
export type RealtimeFeedCollection = components['schemas']['FeedCollection'];
export type RealtimeFeed = components['schemas']['Feed'];

export type RealtimeFullTrajectoryCollection = FullTrajectoryCollection;

export type RealtimeFullTrajectory = FullTrajectory;

export type RealtimeFullTrajectoryCollectionProperties =
  FullTrajectoryCollectionProperties;

export type RealtimeFullTrajectoryProperties = FullTrajectoryProperties;

export interface RealtimeHealth {
  heathly: boolean;
  service: RealtimeService;
  tenant: null | string;
}

export interface RealtimeHealthCheckResponse {
  client_reference: null;
  content: RealtimeHealth;
  source: 'healthcheck';
  timestamp: number;
}

export type RealtimeLine = Line;

export type RealtimeMot = TmotCode;

export interface RealtimeNews {
  incident_program: boolean;
  messages: RealtimeNewsMessage[];
}

export interface RealtimeNewsMessage {
  content: string;
  lines: RealtimeLine[];
  title: string;
  updated: string; // TODO: ISO string
}

export interface RealtimeNewsTickerResponse {
  client_reference: null;
  content: RealtimeNews;
  source: `${RealtimeTenant}_newsticker`;
  timestamp: number;
}

export type RealtimeService =
  | 'redis_websocket_api'
  | 'tralis_fzo'
  | 'tralis_geofox'
  | 'tralis_newsticker'
  | 'tralis_stations'
  | 'tralis_vdv'
  | 'tralis_worker'
  | string;

export interface RealtimeStation extends Feature {
  geometry: Point;
  properties: RealtimeStationproperties;
}

export type RealtimeStationId = number;

export interface RealtimeStationproperties extends Feature {
  elevatorOutOfOrder: boolean;
  elevators: object;
  elevatorState: RealtimeElevatorState;
  hasAccessibility: boolean;
  hasAirport: boolean;
  hasElevator: boolean;
  hasZOB: boolean;
  name: string;
  networkLines: RealtimeLine[];
  tenant: RealtimeTenant;
  transfers: RealtimeTransfer[];
  uic: RealtimeStationId;
}

export interface RealtimeStationResponse {
  client_reference: null;
  content: RealtimeNews;
  source: `station_${RealtimeStationId}`;
  timestamp: number;
}

export type RealtimeStop = StopSequenceCall;

export type RealtimeStopSequence = StopSequence;

export type RealtimeStopSequenceResponse = StopSequenceMessage;

export type RealtimeStopState = TCallStateEnum;

export type RealtimeTenant = '' | 'sbb' | 'sbh' | 'sbm' | string;

export interface RealtimeTimetableResponse {
  client_reference: null;
  content: RealtimeDeparture;
  source: `timetable_${RealtimeStationId}`;
  timestamp: number;
}

export type RealtimeTrainId = string;

export type RealtimeTrajectoryResponse = PartialTrajectoryMessage;

export type RealtimeTrajectoryState = TTrainStateEnum;

export type RealtimeTrajectoryProperties = {
  cancelled: boolean; // to chekc if it commes from backend or if it is generated by the RealtimeAPI class
  coordinate?: number[]; // Prop added when rendered on the map, not in the backend response
  rotation?: null | number; // Prop added when rendered on the map, not in the backend response
} & TrackerTrajectoryProperties;

export type RealtimeTrajectory = {
  properties: RealtimeTrajectoryProperties;
} & TrackerTrajectory;

export interface RealtimeTransfer {
  lines: string[];
  mot: RealtimeMot;
}
